#!/usr/bin/env node

var buf = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', function(chunk){
  buf += chunk;
}).on('end', function(){
  var comments = JSON.parse(buf);
  comments.forEach(function(comment){
    if (comment.ignore) return;
    if (comment.isPrivate) return;
    if (!comment.ctx) return;
    if (!comment.description.full.indexOf('Module dep')) return;
    var ctx = comment.ctx;
    console.log();
    console.log('# %s', ctx.string);
    console.log();
    console.log(comment.description.full.trim().replace(/^/gm, '  '));
  });
  console.log();
}).resume();