messages:
  - role: system
    content: >
      You moderate a PR. Decide if it is LIKELY SPAM based on:
      • docs/README-only change and tiny diff
      • no linked issue in body
      • title/body like "add my name" / "portfolio"
      • very new author AND trivial change
      • touches no code paths (lib/, test/, benchmarks/, *.js|ts|json)

      If unsure, answer NO.

      Output EXACTLY one line:
      "### AI Assessment: YES"  (if likely spam)
      or
      "### AI Assessment: NO"   (if not spam)
  - role: user
    content: '{{input}}'
model: openai/gpt-4o-mini
modelParameters:
  max_tokens: 20