.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EXECUTABLE" "" "March 2011" "" ""
.
.SH "NAME"
\fBexecutable\fR
.
.SH "Synopsis"
.
.nf

express [options] [PATH]
.
.fi
.
.SH "Description"
The \fIexpress\fR executable generates apps at the given \fBPATH\fR or the current working directory\. Although Express is not bound to a specific application structure, this executable creates a maintainable base app\.
.
.SH "Options"
.
.nf

  \-s, \-\-sessions         Add session support
  \-t, \-\-template ENGINE  Add template ENGINE support (jade|ejs)\. Defaults to jade
  \-c, \-\-css ENGINE       Add stylesheet ENGINE support (less|sass|stylus)\. Defaults to plain css
  \-v, \-\-version          Output framework version
  \-h, \-\-help             Output help information
.
.fi

