.TH EXPRESS "1" "March 2013" "express 3.1.0" "User Commands"
.SH NAME
express \- Sinatra inspired web development framework
.SH SYNOPSIS
Usage: express [options]
.SH DESCRIPTION
This Node.js module is a fast, unopinionated, minimalist web development
framework inspired by Sinatra.

The Express philosophy is to provide small, robust tooling for HTTP servers.
Making it a great solution for single page applications, web sites, hybrids,
or public HTTP APIs.

Built on Connect you can use only what you need, and nothing more,
applications can be as big or as small as you like, even a single file.
Express does not force you to use any specific ORM or template engine. With
support for over 14 template engines via Consolidate.js you can quickly craft
your perfect framework.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
output usage information
.TP
\fB\-V\fR, \fB\-\-version\fR
output the version number
.TP
\fB\-s\fR, \fB\-\-sessions\fR
add session support
.TP
\fB\-e\fR, \fB\-\-ejs\fR
add ejs engine support (defaults to jade)
.TP
\fB\-J\fR, \fB\-\-jshtml\fR
add jshtml engine support (defaults to jade)
.TP
\fB\-H\fR, \fB\-\-hogan\fR
add hogan.js engine support
.TP
\fB\-c\fR, \fB\-\-css\fR <engine>
add stylesheet <engine> support (less|stylus) (defaults to plain css)
.TP
\fB\-f\fR, \fB\-\-force\fR
force on non\-empty directory
.SH AUTHORS
The main author of expresso is TJ Holowaychuk <\fBtj@vision-media.ca\fR>.
For a more complete list of contributors, see the GitHub page at
<\fBhttps://github.com/visionmedia/express\fR>
.SH REPORTING BUGS
Please report bugs on the GitHub issue tracker:
<\fBhttps://github.com/visionmedia/express/issues\fR>
