/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function etag(body: string, encoding?: string | undefined | null): string
export function wetag(body: string, encoding?: string | undefined | null): string
export function isAbsolute(path: string): boolean
export function normalizeType(contentType: string): Params
export function normalizeTypes(contentTypes: Array<string>): Array<Params>
export function compileETag(): void
export class Params {
  value: string
  quality?: number
  params: Record<string, string>
}
