/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function isAbsolute(path: string): boolean
export function acceptParams(str: string): Params
export function normalizeType(contentType: string): Params
export function normalizeTypes(contentTypes: Array<string>): Array<Params>
export class Params {
  value: string
  quality?: number
  params: Record<string, string>
}
