var execFile = require('child_process').execFile;
var writeFile = require('fs').writeFile;
execFile('git', ['log', '--reverse', '--format=%aN <%aE>'], function(error, stdout, stderr) {

	var authors = stdout.split("\n")

	var email_authors_map= {};
	var unique_emails = [];
	for (var i=0; i<authors.length; i++) {
		var match = /^.*?(<.*)/.exec(authors[i]);
		if (match) {
			var email = match[1];
			if (!email_authors_map[email]) {
				email_authors_map[email] = [authors[i]];
				unique_emails.push(email);
			} else {
				email_authors_map[email].push(authors[i]);
			}
		} else if (authors[i] !== '') {
			console.error('Ignored: ' + authors[i]);
		}
	}

	var content = "# Authors ordered by first contribution.\n\n";
	for (var i=0; i<unique_emails.length; i++) {
		var authors_for_email = email_authors_map[unique_emails[i]];
		var most_recent_author = authors_for_email[authors_for_email.length - 1];
		content += most_recent_author;
		content += "\n";
	}
	content += "\n# Generated by tools/update_authors.js\n";
	writeFile('AUTHORS', content);
});
