.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "EXECUTABLE" "" "July 2010" "" ""
.
.SH "Synopsis"
.
.nf

express [\-h|\-\-help] [\-v|\-\-version] [PATH]
.
.fi
.
.SH "Description"
The \fBexpress\fR executable generates apps at the given \fBPATH\fR or the current working directory\. Although Express is not bound to a specific application structure, this executable creates a maintainable base app\.
.
.SH "Options"
.
.nf

\-v, \-\-version         Output framework version
\-h, \-\-help            Display help information
.
.fi

