.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "INDEX" "" "July 2010" "" ""
High performance, high class web development for Node\.js \fIhttp://nodejs\.org\fR
.
.IP "" 4
.
.nf

var app = express\.createServer();

app\.get(\'/\', function(req, res){
    res\.send(\'Hello World\');
});
.
.fi
.
.IP "" 0

