name: AI Moderator
on:
  issues: { types: [opened] }
  issue_comment: { types: [created] }
  pull_request_review_comment: { types: [created] }
permissions:
  contents: read
  issues: write
  pull-requests: write
  models: read
jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: github/ai-moderator@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          enable-spam-detection: true
          minimize-detected-comments: true